docs: Add a translation of README in Simplified Chinese
git-goods/gitanimals pull request #144
Opened 2024-09-23 13:49 UTC by Octopus058

2024-09-23 16:11 UTC, devxb requested changes
Thanks for contributions

2024-09-23 16:11 UTC, devxb commented on README.md
> +[English](README-en.md) | **한국어** | [简体中文](READNE-zhcn.md)
I think there is a typo. Please correct it.

```suggestion
[English](README-en.md) | **한국어** | [简体中文](README-zhcn.md)
```

2024-09-23 16:18 UTC, Octopus058 commented on README.md
> +[English](README-en.md) | **한국어** | [简体中文](READNE-zhcn.md)
fixed

2024-09-23 16:22 UTC, devxb commented on README-en.md
> +**English** | [한국어](README.md) | [简体中文](READNE-zhcn.md)
I think there's a typo here too. 😭 

```suggestion
**English** | [한국어](README.md) | [简体中文](README-zhcn.md)
```

2024-09-23 16:27 UTC, Octopus058 commented on README-en.md
> +**English** | [한국어](README.md) | [简体中文](READNE-zhcn.md)
Ah well, maybe have to be tomorrow. I'm too tired to do any work, now is 12pm in my city. If any other typo u found, just comment here, Have a good night my friend :)

2024-09-23 16:34 UTC, devxb commented on README-en.md
> +**English** | [한국어](README.md) | [简体中文](READNE-zhcn.md)
Of course, thank you so much for your interest and contribution, bro

2024-09-24 15:36 UTC, devxb approved these changes
Thanks for contributions @Octopus058 
Have a nice day 😄

2024-09-24 15:37 UTC, merged

2024-09-24 15:38 UTC, Octopus058 commented
u too my friend :D